### ISSUE TITLE
unicode error : unicodeescape' codec can't decode bytes in position

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#100]
Hello,

Here my pipeline
![image](https://github.com/user-attachments/assets/9e802e0b-7049-4bdb-9405-32896e862b58)

Result in console
![image](https://github.com/user-attachments/assets/8bf78e9e-fea5-401e-b470-4bed956ad8b1)

Error message :

> Error

(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1567641760.py, line 14)
[Show Traceback](http://localhost:8888/lab#)

Cell In[14], line 14
excelfileInput1 = pd.read_excel("C:\Users\saubert\aaaaaaa_simon_aaaa.xlsx", engine=None, sheet_name=0, header=0).convert_dtypes()
^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

I have something similar with csv and without env variable
![image](https://github.com/user-attachments/assets/40f8a197-3d7c-4487-89e1-6916881f7cb8)

Last release of amphi.

Best regards,

Simon

**Comment by simonaubertbd** [comment]
files attached 
[aaaaaaa_simon_aaaa.csv](https://github.com/user-attachments/files/16647934/aaaaaaa_simon_aaaa.csv)
[aaaaaaa_simon_aaaa.xlsx](https://github.com/user-attachments/files/16647935/aaaaaaa_simon_aaaa.xlsx)

**Comment by tgourdel** [comment]
Thanks Simon, the files look good, I can open them correctly.
I've looked online and it seems related to Windows and to the string in the filePath: https://stackoverflow.com/questions/37400974/error-unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3

Obviously you shouldn't have to bother so I need to fix something. I'll take a look.

As workaround, It seems you can do the following:
`pandas.read_csv("C:/Users/saubert/aaaaaaa_simon_aaaa.xlsx")`
You need to inverse the slashes

`pandas.read_csv("C:\\Users\\saubert\\aaaaaaa_simon_aaaa.xlsx")`
Or you need to double them

**Comment by simonaubertbd** [comment]
@tgourdel Oh, ok... that's because I wrote myself the adress. If I use the browse from the tool it works.

From tools, the adress is only tests_amphi/aaaaaaa_simon_aaaa.csv and not C:/Users/saubert/tests_amphi/tests_amphi/aaaaaaa_simon_aaaa.csv

I understand I made a mistake but a more clever error message would help.

Best regards,

Simon

**Comment by tgourdel** [comment]
Yeah, for now it only shows the original Python error message which isn't very telling nor user-friendly sometimes 
To address this I had the idea to implement custom messages based on the technical message. 
Not a priority right now, but to keep in mind!! I'll close this one for now :)
Thanks
