### ISSUE TITLE
Update Oracle Input to use python-oracledb

### ISSUE THREAD

**Issue by tgourdel** [amphi-ai/amphi-etl#107]

**Comment by tgourdel** [comment]
Published in 0.5.81

**Comment by amoradell** [comment]
A little glitch when using thick mode : init_oracle_client() should be called from oracledb if this option has been choosen
```
    // Initialize the Oracle client if oracleClient is provided
    const oracleClientInitialization = config.oracleClient && config.oracleClient.trim()
      ? `cx_Oracle.init_oracle_client(lib_dir="${config.oracleClient}")\n`
      : "";
```

**Comment by tgourdel** [comment]
Oh, I thought this option was only available for cx_Oracle! Good catch thanks, will be updated in next release

**Comment by amoradell** [comment]
Thanks, thin mode is default with oracledb but it's possible to use thick mode, especially when using an oracle server < 12 which is quite common in production databases

**Comment by tgourdel** [comment]
Thanks @amoradell, would love to connect and understand your use cases and how I can improve Amphi. Is there somewhere I can reach out? (you can join the slack channel or reach out on [LinkedIn](https://www.linkedin.com/in/thibautgourdel/) or **[email](tgourdel@amphi.ai))**
