### ISSUE TITLE
Type converter : option to deal with unability to convert

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#108]
Hello,

As of today, when you use a type converter to convert a value and it's not possible (like a string 'John' to an integer), Amphi gives an error message

![image](https://github.com/user-attachments/assets/d2bb401b-cd15-4040-8f89-f5c109befe88)

And the pipeline doesn't go further.

However, due to bad data quality, you may want it to continue. Maybe we could add options like that:
"If value can't be converted :
-error and stop
-warning and continue (with x value displayed in console)"
In the second case, unconverted value would give null
Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, that's a good suggestion

**Comment by simonaubertbd** [comment]
@tgourdel Thanks ! I played with it and I have only one little feedback : by default, the option is blank. Shouldn't it be populated ?
![image](https://github.com/user-attachments/assets/88da1594-2c72-4738-8602-a7487b8e5365)
