### ISSUE TITLE
Rename the "Extract" tool to "Text Extract and Regex" or something clearer

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#109]
Hello,

The "Extract" name is somehow confusing.. we can imagine with this name it's some kind of database or file extraction while it's actually a way to extract a string from another string.

Best regards,

Simon

**Comment by tgourdel** [comment]
Renamed in "Parse & Extract" for now, was reluctant to use "Regex" in the name as some people don't know what it is I think. Let me know what you think

**Comment by simonaubertbd** [comment]
@tgourdel Yes, you're right, I wasn't a fan of this regex in name either tbh, "Parse & Extract" is perfect for disambiguation. Thanks!
