### ISSUE TITLE
Extract tool : Length mismatch error

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#110]
Hello,

The pipeline :
![image](https://github.com/user-attachments/assets/7551496d-5cd7-4355-ab72-059efb765d65)

And the error message

> Error

Length mismatch: Expected axis has 2 elements, new values have 1 elements
[Show Traceback](http://localhost:8888/lab/tree/tests_amphi/untitled.ampln#)

---------------------------------------------------------------------------
ValueError Traceback (most recent call last)
Cell In[16], line 27
25 # Extract data using regex
26 extract1_extracted = fillMissingValues1['FirstName'].str.extract(rf"(\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b)")
---> 27 extract1_extracted.columns = ["extract1_1"]
28 extract1 = fillMissingValues1.join(extract1_extracted, rsuffix="_extracted")
30 extract1

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py:6307, in NDFrame.__setattr__(self, name, value)
6305 try:
6306 object.__getattribute__(self, name)
-> 6307 return object.__setattr__(self, name, value)
6308 except AttributeError:
6309 pass

File properties.pyx:69, in pandas._libs.properties.AxisProperty.__set__()

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py:813, in NDFrame._set_axis(self, axis, labels)
808 """
809 This is called from the cython code when we set the `index` attribute
810 directly, e.g. `series.index = [1, 2, 3]`.
811 """
812 labels = ensure_index(labels)
--> 813 self._mgr.set_axis(axis, labels)
814 self._clear_item_cache()

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\internals\managers.py:239, in BaseBlockManager.set_axis(self, axis, new_labels)
237 def set_axis(self, axis: AxisInt, new_labels: Index) -> None:
238 # Caller is responsible for ensuring we have an Index object.
--> 239 self._validate_set_axis(axis, new_labels)
240 self.axes[axis] = new_labels

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\internals\base.py:98, in DataManager._validate_set_axis(self, axis, new_labels)
95 pass
97 elif new_len != old_len:
---> 98 raise ValueError(
99 f"Length mismatch: Expected axis has {old_len} elements, new "
100 f"values have {new_len} elements"
101 )

ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements

Happens also when I choose an exit option
![image](https://github.com/user-attachments/assets/70da35d7-749d-46fd-b006-9fb28f67157b)

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks for reporting Simon, I'll link into it.

**Comment by tgourdel** [comment]
Should be fixed in latest version! Let me know if not
