### ISSUE TITLE
Transform versus Transforms tool categories

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#113]
Hello,

Here what I have at 1st level for tool categories :
![image](https://github.com/user-attachments/assets/1451cd95-3aca-4297-9982-3a97acc52298)

As you can see, there are two categories : Transform and Transforms (I think the -s one is correct)

The one without a s only contains one tool :
![image](https://github.com/user-attachments/assets/7ecae49e-9557-47ce-9fda-075744957544)

Best regards,

Simon

**Comment by tgourdel** [comment]
You don't miss a thing 😳
Thanks for catching this

**Comment by tgourdel** [comment]
Thanks @simonaubertbd. Got fixed a few versions ago!!
