### ISSUE TITLE
Excel input : ability to retrieve sheets(and named zone) by name with a drop down menu

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#129]
Hello,

as of today, we can retrieve excel sheets by number (0 for 1st sheet, etc)

However, what would be really helpful would be to specify sheet name, with a drop down menu. Can we have an option for that ?

![image](https://github.com/user-attachments/assets/34aef9fb-cc9b-4652-a2bf-135750a7e22e)

![image](https://github.com/user-attachments/assets/84720c32-620c-4e28-b8e0-c85d35c5138a)

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, I'll definitely asd it on the short term, along with table lists for databases as well

**Comment by simonaubertbd** [comment]
@tgourdel When you will work on it, can you also add the ability to have the list of sheet names as on the screenshot? 
Best regards,

Simon

**Comment by tgourdel** [comment]
@simonaubertbd what's "named zone" that you mentioned in the title?

**Comment by simonaubertbd** [comment]
Hello @tgourdel 
it's basically a bunch of cells together that you can name :
![image](https://github.com/user-attachments/assets/9e3a2928-12cd-4dc7-b2e9-8958947fd7b4)
However, my bad, the english name is named range.

Very useful when your sources is actually an excel document (invoice, etc).

Best regards,

Simon

**Comment by tgourdel** [comment]
Interesting, didn't know it existed

**Comment by tgourdel** [comment]
Excel input now provide a drop down list for selecting sheets. Can also select multiple sheets. Available in 0.8.21.

Named range not available now. Let's create a different issue for it!

Thanks Simon
