### ISSUE TITLE
Excel file output : space on the first column

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#131]
Hello,

I'm not sure why but I have some space before the text on my first column.
![image](https://github.com/user-attachments/assets/aa02f7f6-b069-4f07-9ca0-3a5908605c1d)
![image](https://github.com/user-attachments/assets/17cb59be-dd5d-41e2-b088-e72ecf6b617e)

Result :
![image](https://github.com/user-attachments/assets/2316274e-55be-4a7f-939e-50d7c1d3bc8f)
[test_excel_output.xlsx](https://github.com/user-attachments/files/16834517/test_excel_output.xlsx)

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, trying to find the issue for that, looks like it is coming from the Inline Input since it does the same when outputing in CSV

**Comment by tgourdel** [comment]
Couldn't reproduce this one. Either it got fixed somewhere else or I missed something. Please reopen if you see this error again. Thanks

**Comment by simonaubertbd** [comment]
@tgourdel  I confirm : I don't reproduce it either. Thanks !
