### ISSUE TITLE
Formula tool : color highlighting

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#132]
Hello,

As of today, you can write expression in formula. However, it's not that easy to read, you don't know if something is a function, a value, a field, etc..

What would be nice to solve that is color highlighting like that :
![image-76](https://github.com/user-attachments/assets/2a340c83-517e-4673-8da3-9d3f15a60df1)

For reference, coming from #27 

Best regards,

Simon

**Comment by simonaubertbd** [comment]
@tgourdel some documentations here
https://wiki.python.org/moin/PyQt/Python%20syntax%20highlighting

**Comment by tgourdel** [comment]
That was an oversight, it should have been there. I've added it! The same color highlighting is available in code blocks.
Thanks for reporting Simon

**Comment by simonaubertbd** [comment]
@tgourdel That's pretty cool, thanks a lot !!
