### ISSUE TITLE
Date Conversion tool

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#134]
Hello,

Converting text to date or date to text is a very common task. We can do that through formula but it's not that straightforward since there are many formats. Having a visual help would be a huge advantage.

Here an example :
![image](https://github.com/user-attachments/assets/44ec2c11-eecc-485b-8b9b-da041033d1ee)

We can even do better with the ability to select different fields at once.

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi @simonaubertbd, I've introduced a DateTime Converter component in the last version (0.6.0). Hope it works well, let me know if you encounter any issues or have any feedback

**Comment by simonaubertbd** [comment]
@tgourdel Thanks, really nice tool that will simplify life with dates. But you know me, yep, I have three feedbacks 😄 
-maybe a way to choose the name of the new column when new column is checked
-when it's date to string=>only retrieve date fields
-when it's date to string=> I noticed the field is an "object" and not a string. Don't know if it's a bug or feature.
-I'm not sure to understand the impact of the language drop down menu?

Do you want me to create distinct issues for all of that ?

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, fair points for the first 2 :D 
The object type is definitely a miss, should be a string!
The language is needed (if i'm not mistaken) for the formats using month and days names (January vs Janvier)
