### ISSUE TITLE
Console doesn't display anything

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#137]
Hello,

Since the last release (0.5.95) , the lower console doesn't display anything :
![image](https://github.com/user-attachments/assets/2957c0dc-da31-4aec-b172-89dc8b59844c)

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon, does it work most of the time and you got this error once or you never see the console anymore?

**Comment by tgourdel** [comment]
Should be fixed in 0.5.96, sorry about that. Happens in the build process sometimes and haven't found the reason why.
