### ISSUE TITLE
Annotation : an easy way to delete it

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#139]
Hello,

I have played a lot with annotation these last days and after a few tries, I don't manage to delete it from the pipeline. It doesn't have a x like the other tools, suppr doesn't work..

I don't know if there is a simple way to do it and I missed it or if it's a feature request.

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon, you should be able to delete it with "backspace" or the delete button. Let me know if that doesn't work for you, might be a miss on my part for Windows :s

**Comment by simonaubertbd** [comment]
Hello @tgourdel and thanks !  I just learnt the backspace keyboard shortcut. Do you have the ability to add it to the keyboard shortcut list ?

![image](https://github.com/user-attachments/assets/370cf4ce-1baf-463c-92b7-6a7d384bf9fa)

Also, maybe the x like the other tools would be a good idea, since it's consistent.

Best regards,

Simon

**Comment by tgourdel** [comment]
Ah! That's a good point, it's not in this list. Noted
I've added the "del" key for the next release as well !
Yeah I was hesitating but I can definitely add a cross when the annotation is selected. I'll keep this open until I add those.
Thanks a lot

**Comment by Mika97400** [comment]
Looked arround a minutes to find backspace was the key to remove annotation! 😅

**Comment by tgourdel** [comment]
Will definitely add something more straightforward :D

**Comment by tgourdel** [comment]
Hi everyone, I've added a button on the top right corner in v0.6.0! Thank you for flagging this :) 
Let me know if you have feedback!!
Thanks

**Comment by simonaubertbd** [comment]
@tgourdel Thanks, I love it ! Will you add the keyboard shortcut in the next release or do you prefer I open an issue?

**Comment by tgourdel** [comment]
Oh right, I forgot about it!! Yes please, let's open a new issue :)
Thanks @simonaubertbd
