### ISSUE TITLE
Component SELECT COLUMN have a bug after renaming a field

### ISSUE THREAD

**Issue by Mika97400** [amphi-ai/amphi-etl#145]
Hello,

After renaming a field in source (excel file) even after refreshing selected columns with the new field, you get an error :

Error
invalid syntax. Perhaps you forgot a comma? (3431119965.py, line 62)
[Show Traceback]

You must drop the component and recreate it to remove the error.

Best regards.

**Comment by tgourdel** [comment]
Hi @Mika97400, thanks for reporting. Would you be able to show the code generated that causes the issue?

**Comment by Mika97400** [comment]
It looks like python code don't refresh :

![Capture d'écran 2024-09-18 111040](https://github.com/user-attachments/assets/97268fda-ad5f-4f38-924d-1c80198d181f)
![Capture d'écran 2024-09-18 111240](https://github.com/user-attachments/assets/f90f53e1-7603-4920-b8eb-7d29226b31a4)
![Capture d'écran 2024-09-18 111708](https://github.com/user-attachments/assets/e29e6032-ab49-456e-b9d4-cd61dd0fcf60)

**Comment by tgourdel** [comment]
Thank you, I've been able to reproduce, will fix ASAP.

**Comment by tgourdel** [comment]
@Mika97400, should be fixed in 0.6.0. Let me know if otherwise :)
Thanks for reporting!
