### ISSUE TITLE
Issue with Aggregate Row Function

### ISSUE THREAD

**Issue by bipiniiith** [amphi-ai/amphi-etl#148]
![Untitled](https://github.com/user-attachments/assets/4da072ae-718d-48fa-a78d-65d2aed88b8d)
The "Operations" function remain inactive unless we select another column from table. Also the output of the Sum operation is also wrong even after grouping based on two columns.

**Comment by tgourdel** [comment]
Hi @bipiniiith, thank you for reporting this issue.
I'm surprised, are you able to share any more information so that I can try to replicate?
Could you share the relevant part of the generated code by clicking on the "Export to Python code" button?

**Comment by bipiniiith** [comment]
Hi,
Please find; also attached the .csv data file for replicating. 

# Source code generated by Amphi
# Date: 2024-09-19 16:26:54
# Additional dependencies: s3fs
import pandas as pd
import duckdb

# Reading data from Desktop/clinical_data.csv
csvFileInput1 = pd.read_csv("Desktop/clinical_data.csv", sep=",").convert_dtypes()


# Filter and order columns
filterColumn1 = csvFileInput1[["Study ID", "Patient ID", "Sample ID", "AgeatDiagnosis", "Cancer Type", "Disease Free status", "Disease Free Survival (Months)", "ESTIMATE Score", "Mutation Count", "Mutation Load", "Overall Survival (Months)", "Sex", "Overall Survival Status", "Treatment", "Tumor Site", "Tumor Stage"]]

# Execute SQL Query using DuckDB
sqlQuery1 = duckdb.query("SELECT * FROM filterColumn1 where AgeatDiagnosis < 40;").to_df().convert_dtypes()
aggregate1 = sqlQuery1.groupby(["Sex"]).agg(Tumor_Site_sum=('Tumor Site', 'sum')).reset_index()

[clinical_data.csv](https://github.com/user-attachments/files/17057889/clinical_data.csv)

**Comment by tgourdel** [comment]
Hi @bipiniiith, I've reproduced your pipeline, but it looks good to me?
Could you detail what was wrong for you? (did you get an error or do you think the result is wrong)

**Comment by bipiniiith** [comment]
It worked. Thanks.
