### ISSUE TITLE
JSON Flattening

### ISSUE THREAD

**Issue by amoradell** [amphi-ai/amphi-etl#149]
Is it possible to create a JSON flattener component with pandas and use json_normalize ?
[pandas.json_normalize](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html)

I have sometimes fields with JSon data and I want to flatten them to transfer into csv files.

Thanks

**Comment by tgourdel** [comment]
Hi @amoradell,
Thanks for the suggestion, that's a good idea. Will look into it

**Comment by tgourdel** [comment]
Available in 0.8.5 under Transforms.JSON
