### ISSUE TITLE
DateTime Converter : ability to choose the name of the new field

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#152]
Hello,

It's really nice to choose if we create a new column or overwrite the existing one but on the first choice (a new column), I would like to choose its name. Right now, it's the same with "_converted".

Best regards,

Simon

**Comment by Mika97400** [comment]
Hello,

Not sure I understand your request but maybe you should use  "Formula row" to create new column where you can set all these parameters, a simple example translating to string if it can help :

![image](https://github.com/user-attachments/assets/bd4ec22c-2eef-460e-8a24-cded0023cd05)

![image](https://github.com/user-attachments/assets/4efad1f9-d57f-4292-a35e-c5741a07a09d)

**Comment by tgourdel** [comment]
Available in 0.8.6! Thanks Simon

**Comment by simonaubertbd** [comment]
@tgourdel  thanks !
