### ISSUE TITLE
DateTime Converter : date to string gives an object and not a string

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#153]
Hello,

When converting a date to a string, the result is an object field, not a string field.

Best regards,

Simon

**Comment by Mika97400** [comment]
Hello,

It seems to work, what date format / separator are you using ?

![image](https://github.com/user-attachments/assets/925ccee8-dd6a-4ce5-9162-4fb37525ac7f)

**Comment by simonaubertbd** [comment]
@Mika97400 Actually, you can"t see that in excel ;)

Object is a python notion
![image](https://github.com/user-attachments/assets/9475b6e2-9bfa-4473-80dc-e780e83b46d7)


Best regards,
Simon

**Comment by Mika97400** [comment]
I'm not up to date and don't have the Datetime converter, sorry for responding off topic

**Comment by tgourdel** [comment]
Yeah, the object type is a mixed type used by pandas, however for Amphi I decided to use string which is clearer and more standard. In this case I missed the fact that it was returning an object type instead of string! Thanks for reporting :)

**Comment by tgourdel** [comment]
Fixed starting with 0.7.0!
Thanks for reporting @simonaubertbd
