### ISSUE TITLE
Annotation is now in Configuration category

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#157]
Instead of Documentation category on 0.7

![image](https://github.com/user-attachments/assets/4bc683bf-cc71-4a7b-81eb-019cee1f8d71)

Best regards,

Simon

**Comment by tgourdel** [comment]
Yes, I did it on purpose to simplify a bit? Doesn't make sense?

**Comment by simonaubertbd** [comment]
@tgourdel Well, that's not exactly a configuration thing, since it's basically free and I can't break the pipeline with it. I like the idea of having a dedicated Documentation category. It can be used in the future for some metadata on the pipeline as well such as #56 
Also, you can show that way that documentation is important.

Best regards,

Simon

**Comment by tgourdel** [comment]
Alrighty, put back where it belongs ;)
