### ISSUE TITLE
Transpose should accept key fields

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#158]
Hello,

As of today, Transpose switch columns and rows like that
![image](https://github.com/user-attachments/assets/d31ad0a3-6a5a-44dc-ba82-6abee950a5b1)

![image](https://github.com/user-attachments/assets/e71a4c33-0d12-4ef6-9625-5e1e3ca97a89)

However, most of the time (to be frank, every time), I would like to specify a key (here my id) to have something more like that :
![image](https://github.com/user-attachments/assets/311746bb-c08c-4cef-8e8f-132c43c9cac7)

This is way more useful.

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon, isn't it what can be done via the Pivot?

**Comment by simonaubertbd** [comment]
Hello @tgourdel Pivot works the other way, from rows to columns 

![image](https://github.com/user-attachments/assets/be10e0a9-65af-4b93-8965-6fe692a3fecf)


That's why different icons as mentioned in  #88 are important ;) One always forget which one does the thing.

**Comment by tgourdel** [comment]
Added in 0.8.4, I've tested with a few examples and seemed to be working. Let me know if you encounter any issues.

**Comment by simonaubertbd** [comment]
Hello @tgourdel  That's far better, we can really use it now. Thanks !
![image](https://github.com/user-attachments/assets/67174f6f-8eab-4bcd-beba-c6216fdece4f)
