### ISSUE TITLE
Sample options : group and percent

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#159]
Hello,

A few additions that would help when sampling a dataset :
![image](https://github.com/user-attachments/assets/81760c4a-b976-445b-b194-d16966e2741e)

Basically, it's mainly

-using percent instead of a number

-group : you may want a percent of data by category or by period in order to have a more representative sample.

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks for the suggestion @simonaubertbd

**Comment by tgourdel** [comment]
Alright, I've updated the sample component in v0.8.4 to support row number and percentage. 

Also added the ability to Group By columns. From my tests, it seems to work as expected but let me know otherwise.

![image](https://github.com/user-attachments/assets/4202342f-6875-484c-980a-6bd444673955)

**Comment by simonaubertbd** [comment]
@tgourdel Works fine for me, thanks a lot !
