### ISSUE TITLE
Summary tool : pivot the output

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#176]
Hello,

Love the new summary tool. 

![378398515-1b294346-7639-40e1-afaf-4f1dda69838b](https://github.com/user-attachments/assets/c53d5b95-9f6c-4630-ba4e-03634a08cbc1)

I would prefer a pivoted vision, like one row by field (and a column for the field types). Two reasons : in terms of UI, it's easier to scroll down than right and it's also a data exploration/investigation tool.. so next, i may filter the fields with N/a or something like that.

Best regards,

Simon

**Comment by tgourdel** [comment]
Done! Followed your advice and pivoted the output by default but still left the option to change it :)
Thanks!

**Comment by simonaubertbd** [comment]
Hello @tgourdel I love it ! Thanks !
![image](https://github.com/user-attachments/assets/13538285-f399-46c2-baea-bc3d0226c93d)
