### ISSUE TITLE
Summary tool in a dedicated category

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#177]
Hello,

As of today, the Summary tool is in the Transform category.
I would place the tool in a new Data Exploration (or investigation) category instead of Transform. 

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks, I followed your recommendation ;)

**Comment by simonaubertbd** [comment]
@tgourdel  Thanks to you, that's nice !
![image](https://github.com/user-attachments/assets/92876de0-73e5-4f4d-8acf-6a14ea770002)
