### ISSUE TITLE
[Feature Request] Add Endpoint url parameter for Minio using S3 File input

### ISSUE THREAD

**Issue by Noobzik** [amphi-ai/amphi-etl#186]
One of my student reported me that they can't use a specific endpoint in order to use Minio
So I suggest adding a new parameter `endpoint_url` which they can fill if they are not using AWS as a cloud provider

**Comment by tgourdel** [comment]
Hi @Noobzik, just checked, I will add a the ability to provide a custom endpoint to support Minio! Thanks for reporting

**Comment by tgourdel** [comment]
Available in 0.8.7, let me know if you encounter any issues!

**Comment by Noobzik** [comment]
Confirmed working
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/75d54ebe-6f8e-4d61-9923-b9548abcb72c">
