### ISSUE TITLE
Rename Excel File Input to reflect other format

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#188]
Hello,

I just discovered that we can now read opendocument files such as .ods. I must say i like it !
![image](https://github.com/user-attachments/assets/7ca7b823-5244-4289-b12a-5dca88e81589)

However, it's not reflected in the tool name. Maybe "Excel/ODS File Input" would be better?

Best regards,

Simon

**Comment by tgourdel** [comment]
That's a good point 🧐 
Just afraid of the looks and readability, I'll do a few tests.
Thanks Simon
