### ISSUE TITLE
Frequency table

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#190]
Hello,

A nice tool for data discovery : it gives for each selected field the frequency of each value :
![image](https://github.com/user-attachments/assets/6deeee8d-114b-4e99-8cdd-3020b2a0b332)

Best regards,

Simon

**Comment by tgourdel** [comment]
Available in 0.8.17!
Thanks Simon

**Comment by simonaubertbd** [comment]
@tgourdel Thanks, that was fast !!
Just a question : shouldn't the Field Name and Field value be text and not object ? (Not sure, I'm not a python dev)
![image](https://github.com/user-attachments/assets/931072b6-b93e-4e9d-bdc4-33fb9def1b94)

Best regards,

Simon

**Comment by tgourdel** [comment]
It should be a string because that's the convention I chose for Amphi. it's not really an issue as object is a default type of mixed text attributed by pandas. I'll fix this in the next version :)
