### ISSUE TITLE
Summary tool : default column type to "all types"

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#191]
Hello,

As of today, the default configuration for column types is "Numerical only"
![image](https://github.com/user-attachments/assets/2dc16bb4-5628-44c9-9ee4-70366c4fd81e)

But 90% of time, you want a summary for all type of fields. and default should be "all types"
![image](https://github.com/user-attachments/assets/d4ae7894-ec74-48c9-a515-6303e1de263c)

Best regards,

Simon

**Comment by tgourdel** [comment]
Mhh that's a good point, now I'm trying to remember why I decided for Numerical only to be the default. I probably thought that's what most people were looking after by default :)

**Comment by simonaubertbd** [comment]
@tgourdel Thanks
