### ISSUE TITLE
Creating folder path for outputs on runtime

### ISSUE THREAD

**Issue by DuSegura** [amphi-ai/amphi-etl#20]
Hi Thibaut:

 I don't know if this was requested before but it would be great to have the pipeline to create the folder of the destination during runtime.

**Comment by simonaubertbd** [comment]
+1. Not hard to develop, a lot of frustration away ;)

**Comment by tgourdel** [comment]
I've added an option for all the file outputs to create the folders if don't exist. The option is off by default for now. Thanks for the suggestion :)

**Comment by tgourdel** [comment]
Will create a new release soon with the changes.

**Comment by tgourdel** [comment]
Released in 0.4.5
