### ISSUE TITLE
Error at install with pip on 0.8.21

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#209]
Hello,

Here what I met with the last release

![image](https://github.com/user-attachments/assets/f92de600-0dbb-4b6c-ae2f-edbf9b113a27)

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ollama 0.3.3 requires httpx<0.28.0,>=0.27.0, but you have httpx 0.28.0 which is incompatible.`

Isn't ollama outdated?
https://pypi.org/project/ollama/#history
Best regards

Simon

**Comment by tgourdel** [comment]
Hi Simon, I'm surprised by the error since I don't think amphi-etl is dependent on ollama's package. So I'm wondering where it comes from

**Comment by tgourdel** [comment]
what might be happening is the new amphi-etl version require httpx 0.28.0 because it'es based on the latest version of JupyterLab which then gets in conflict with the Ollama version you have installed in your environment. Can ou upgrade Ollama?

**Comment by tgourdel** [comment]
https://github.com/jupyterlab/jupyterlab/issues/17035

**Comment by simonaubertbd** [comment]
@tgourdel Yoy may be right, totally forgot I installed ollama. I removed it and it's ok
