### ISSUE TITLE
Cloud inputs and output

### ISSUE THREAD

**Issue by DuSegura** [amphi-ai/amphi-etl#21]
Hi Thibaut. 

I think it would be great to have cloud sources and targets, specifically data lake ones from the main cloud providers. 

I know this is challenging because you would need to deal with security configurations for each cloud but it would be useful.

**Comment by tgourdel** [comment]
Hi @DuSegura, S3 will come very shortly. I'm indeed working on the connections management to deal with security before tackling the cloud inputs. Thanks a lot

**Comment by antonisar** [comment]
Related to #57 smart_open supports many cloud backends in a unified way

**Comment by tgourdel** [comment]
Hi everyone, I've added support for S3 for all file inputs (using the native pandas capabilities for now). 
@antonisar I plan to use smart_open in different components (orchestration components). Thanks for the suggestion
