### ISSUE TITLE
Save the code module I wrote

### ISSUE THREAD

**Issue by zouyujiang** [amphi-ai/amphi-etl#31]
Hello, It's an honor to come across such a great program framework.
I wrote some custom Python code components, I want to save it to the right component bar, the next time a new project can directly drag these components into use.
![01](https://github.com/amphi-ai/amphi-etl/assets/52795601/850c62f4-c961-4531-914b-6793e1ebab1d)

**Comment by tgourdel** [comment]
Hi @zouyujiang, thanks for testing Amphi! Custom components is one the most requested feature, so we'll try to implement it as soon as possible!

**Comment by tgourdel** [comment]
Hi @zouyujiang, I just release a new feature to save components as file:
![image](https://github.com/user-attachments/assets/ad07851c-34c6-4abb-8a24-2fb50b8d2e09)
If you right click on a component you will save a component as a file that you can name. Then you can drag and drop this file on canvas. The component does not appear on the right sidebar but will consider a mechanism to do so in the future. Thank you for the suggestion
