### ISSUE TITLE
Excel File Output : incorrect option for sheet name

### ISSUE THREAD

**Issue by amoradell** [amphi-ai/amphi-etl#32]
Excel File Output component doesn't use correct name for sheet_name option

it uses "sheet" instead of "sheet_name"

- incorrect 
`sqlQuery1.to_excel("c:/dev/db/localites2.xlsx", index=False, sheet='Feuil1')`
- correct
`sqlQuery1.to_excel("c:/dev/db/localites2.xlsx", index=False, sheet_name='Feuil1')`

**Comment by tgourdel** [comment]
Thanks for reporting, it's been fixed in the latest version:
`pip install --upgrade --force-reinstall amphi-etl` (or jupyterlab-amphi if using Jupyterlab)

**Comment by amoradell** [comment]
I add engine = "xlsxwriter" option to pandas to_excel to compare with openpyxl
