### ISSUE TITLE
Your project is not open source, as it uses Elastic License 2.0

### ISSUE THREAD

**Issue by oyarsa** [amphi-ai/amphi-etl#33]
The Elastic License 2.0 is not open-source compliant, so calling your project open-source is incorrect.

The first item in the [license's Limitations section](https://www.elastic.co/licensing/elastic-license):

> **Limitations**
> 
> You may not provide the software to third parties as a hosted or managed service, where the service provides users with access to any substantial set of the features or functionality of the software. 

Directly contradicts the [Open Source Initiative's definition of open-source](https://opensource.org/osd):

>  **1\. Free Redistribution**
> 
> The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.

More commentary on this issue:

https://news.ycombinator.com/item?id=40724610
https://funnelfiasco.com/blog/2021/02/03/thoughts-on-elastic-license-v2/
https://news.ycombinator.com/item?id=36760635

I'm not making any judgement of _why_ you chose this license, merely the fact that you advertise yourselves as open-source when you're not.

**Comment by tgourdel** [comment]
Thank you for the constructive feedback; it's rare these days. I see this raises a lot of emotions. I'll consider other licenses or changing my wording. Thanks.
