### ISSUE TITLE
Excel File Input more options: select engine (incl. calamine), usecols, skiprows, decimal, etc

### ISSUE THREAD

**Issue by TriSSS91** [amphi-ai/amphi-etl#37]
Hello! Thanks for the nice ETL tool.

It will be great to add more options (according pandas library) to select for **Excel File Input**:

1. **engine** - option to select specific engine for pandas to read Excel file ('pyxlsb', 'openpyxl', 'calamine'), setting 'calamine' as default engine, because of it's amazing speed (pls, see [python-calamine](https://github.com/dimastbk/python-calamine) )
2. **usecols** - for selecting wich column to read from Excel file
3. **skiprows** - for skiping some rows from a head of a sheet
4. **decimal** - for correct parsing Europian-style TEXT to numeric
5. **dtype_backend** - for selecting 'numpy' or 'pyarrow' backend

**Comment by tgourdel** [comment]
Engine selection is now possible in the latest version 0.4.7.
pip install --upgrade --force-reinstall amphi-etl

Keeping open to address the other options. I'm considering adding a universal parameter specifier to be able to add regular pandas options without cluttering the UI with options rarely used.

**Comment by TriSSS91** [comment]
> Engine selection is now possible in the latest version 0.4.7. `pip install --upgrade --force-reinstall amphi-etl ` Keeping open to address the other options. I'm considering adding a universal parameter specifier to be able to add regular pandas options without cluttering the UI with options rarely used.

Didn't find engine selection in version 0.4.7 in UI:
![image](https://github.com/amphi-ai/amphi-etl/assets/63854410/d328f695-64c3-427d-90d0-a75f4872affc)

**Comment by tgourdel** [comment]
Thanks @TriSSS91, looks like the the update didn't work as I thought. Would you be able to try this:
`pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi`

**Comment by TriSSS91** [comment]
> Thanks @TriSSS91, looks like the the update didn't work as I thought. Would you be able to try this: `pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi`

Tried to do this, pip shows version 0.4.7 for both amphi-etl and jupyterlab-amph, but UI is still the same.

**Comment by tgourdel** [comment]
Could you try again and check if you finally get the option?  Thank you for your patience
`pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi`

**Comment by TriSSS91** [comment]
> Could you try again and check if you finally get the option? Thank you for your patience `pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi`

Thanks! Now engine selection is avaliable in UI. 
But sometimes it works great, and sometimes (same data, same pipline) - got an error:

`ERROR: Could not find a version that satisfies the requirement calamine (from versions: none) ERROR: No matching distribution found for calamine`

Maybe the reason is that python module name is `python-calamine`, and we need to import it. And the `calamine` is the alias we use in engine option.

**Comment by tgourdel** [comment]
Thanks for this feedback, I had checked the issue and I believe fixed it. It was more a warning since it was not impacting the pipeline indeed showing an error message. I believe it's been fixed, but if it's not the case please reopen and let me know.

**Comment by tgourdel** [comment]
Have added most of the remaining options for the Excel file input in 0.8.21
