### ISSUE TITLE
Excel File Output : add engine option

### ISSUE THREAD

**Issue by amoradell** [amphi-ai/amphi-etl#43]
Default engine is openpyxl but Excel shows a warning when reading file saved with this engine.
When I use xlsxwriter as engine, no warning

`filter2.to_excel("c:/dev/db/localites3.xlsx", sheet_name="cp_multi_localites", engine = "xlsxwriter")`

**Comment by tgourdel** [comment]
Hi @amoradell, thanks for your suggestion. It's been added in the latest version: 0.4.7. I actually chose xlsxwriter as the default engine.
You can update with:
`pip install --upgrade --force-reinstall amphi-etl`
