### ISSUE TITLE
Excel File Input: sheet and header arguments error

### ISSUE THREAD

**Issue by TriSSS91** [amphi-ai/amphi-etl#44]
Some problems with reading Excel.

1. Got an error, when choosing **sheet** option in **Excel File Input**:

```
Error
read_excel() got an unexpected keyword argument 'sheet'
[Show Traceback](http://localhost:8888/lab#)
---------------------------------------------------------------------------
TypeError Traceback (most recent call last)
Cell In[2], line 7
1 # Source code generated by Amphi
2 # Date: 2024-06-25 09:31:25
3 # Additional dependencies: openpyxl
4 import pandas as pd
----> 7 excelfileInput1 = pd.read_excel("dq_report.xlsx", sheet=' Sheet1', header='0').convert_dtypes()
9 excelfileInput1

TypeError: read_excel() got an unexpected keyword argument 'sheet'
```

Maybe `pd.read_excel()` is looking for `sheet_name` argument instead of `sheet` argument:

`pd.read_excel("dq_report.xlsx", sheet_name='Sheet1', header='0').convert_dtypes()`

2. When we add&choose Custom sheet, library adds space in the start of the sheet:

![image](https://github.com/amphi-ai/amphi-etl/assets/63854410/a9a61e86-326d-47cf-b63f-9984522ed9d6)

3. We'll got erros for sheet / header argemument, because all arguments are transformed to strings (instead of int, string, list):

![image](https://github.com/amphi-ai/amphi-etl/assets/63854410/88204870-e2b4-43c4-b28a-02c3234a7016)

![image](https://github.com/amphi-ai/amphi-etl/assets/63854410/1a838e49-62aa-41d7-902c-cd375678907b)

**Comment by tgourdel** [comment]
Thanks @TriSSS91, sorry you face this error. This error actually got fixed recently, see #32 (https://github.com/amphi-ai/amphi-etl/issues/32).

I believe the update didn't work as mention in the other issue. Could you please to try to update both amphi-etl and jupyterlab-amphi:
`pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi `

**Comment by tgourdel** [comment]
Deleted my previous comment. Thanks for reporting, my bad, this error has been fixed for the output not the input :/  (#32)

**Comment by tgourdel** [comment]
Should be fixed in 0.4.8.
`pip install --upgrade --force-reinstall amphi-etl jupyterlab-amphi`

**Comment by TriSSS91** [comment]
Checked different scenarious:

`header`:

- header as number - works good
- header option "None (no header) - doesn't work and return an error (maybe, the reason is that Python generated code is `header='None'`, but we need to generate `header=None`):

> ValueError: header must be integer or list of integers


`sheet_name`:

- sheet number - works good
- sheet name (text) - works good
- list of sheets (for example `['Sheet1']`) - got an error (because we got a Dict of DataFrames, and can't `use .convert_dtypes()` ):

> Error
> 'dict' object has no attribute 'convert_dtypes'
> [Show Traceback](http://localhost:8889/lab#)
> ---------------------------------------------------------------------------
> AttributeError Traceback (most recent call last)
> Cell In[58], line 7
> 1 # Source code generated by Amphi
> 2 # Date: 2024-06-28 17:32:22
> 3 # Additional dependencies: openpyxl
> 4 import pandas as pd
> ----> 7 excelfileInput1 = pd.read_excel("dq_report.xlsx", engine='openpyxl', sheet_name=['Sheet1'], header=0).convert_dtypes()
> 9 excelfileInput1
> 
> AttributeError: 'dict' object has no attribute 'convert_dtypes'

**Comment by tgourdel** [comment]
@TriSSS91 Hi, it should be fixed since last week. When specifying list of sheets, the sheets are concatenated using:
https://pandas.pydata.org/docs/reference/api/pandas.concat.html
