### ISSUE TITLE
Easy way to retrieve amphi version

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#47]
Hello,

It's not that easy to find the version of amphi I'm running.

Maybe it would be nice to have it on the homepage and in an "About" item in the upper menu.

Best regards,

Simon

**Comment by tgourdel** [comment]
Yep, definitely! Needed for debugging users

**Comment by tgourdel** [comment]
Now available in release 0.5.61.

Header menu -> Help -> About Amphi

![image](https://github.com/user-attachments/assets/03b4bfa1-e46b-4eae-bcd7-af4d461e21c2)

Thanks Simon!

**Comment by simonaubertbd** [comment]
@tgourdel thanks !
