### ISSUE TITLE
Tool searching

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#50]
Hello,

There is a lot of tools, which is nice. However, especiall on a small screen, you have to scroll and read them all to find the good one. A search would be a nice feature.

![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/40f93fe9-53e6-41a0-8639-02256db49722)

Best regards,

Simon

**Comment by tgourdel** [comment]
Released in the 0.5! Thanks for the suggestion :)

**Comment by simonaubertbd** [comment]
@tgourdel  Hey, thanks, I love the new tool bar :)
