### ISSUE TITLE
Field summary/overview tool

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#53]
Hello,

it's useful to have a tool to have some insight about the data :
-min/max
-average/mean/median/standard deviation
-type
-count non null/count distinct
-min and max length
-etc...
And that for the selected fields, with an ability to use a sample.

here an example on Alteryx but it also exists on Orange Data Mining :

![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/22ec1248-df1c-4f7f-8f27-47c9d1cb9e87)

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, would definitely be super useful!

**Comment by tgourdel** [comment]
Hi Simon, wondering, is this useful to have it in a pipeline? Or do you just need the stats to design the pipeline?

**Comment by simonaubertbd** [comment]
Hello @tgourdel I think that would be nice to have it in a pipeline like any other tools. That can help for comparison of metadata, or any work on metadata. 

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, released a first version in 0.8.2

**Comment by simonaubertbd** [comment]
hello @tgourdel  Thanks

That works !
![image](https://github.com/user-attachments/assets/1b294346-7639-40e1-afaf-4f1dda69838b)


Of course, since I like to annoy you ^^ I have two remarks (I will create the isssue later)
-I would prefer a pivoted vision, like one row by field (and a column for the field types). Two reasons : in terms of UI, it's easier to scroll down than right and it's also a data exploration/investigation tool.. so next, i may filter the fields with N/a or something like that.
-I would place the tool in a new Data Exploration (or investigation) category instead of Transform.

Best regards,

Simon
