### ISSUE TITLE
Record ID tool

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#54]
Hello,

A very, very simple tool that just create an Id (usually an integer) for each records on the stream. The configuration can be quite simple like just the name and the type.

![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/78eb7dbc-d68e-422b-88a9-7b8c7347202c)

Best regards,

Simon

**Comment by tgourdel** [comment]
Added a Generate ID Column with your suggested fields. We'll probably extend this component with more options such as uuid in the future. Thanks
![image](https://github.com/user-attachments/assets/143fc0b2-2777-43e1-b7c2-673bea0e6595)

**Comment by simonaubertbd** [comment]
@tgourdel Thanks. simple and efficient.
