### ISSUE TITLE
Failed to load the jupyterlab-git server extension.

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#60]
Hello,

Just installed the last release on windows 11 with pip 23.2.1 and I get this message
![image](https://github.com/user-attachments/assets/9f71726a-c666-454e-8832-7587790723f5)

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon, thanks for the report. Does it prevent you to use the app after dismissing the popup?
Also, did the git extension worked fine in the previous releases?

**Comment by simonaubertbd** [comment]
Hello @tgourdel  The app worked fine after I clicked on dismiss and I don't know the exact situation before. All I can say is I didn't try to use the extension and no error message.

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon, coming to you on this issue.
jupyterlab-git isn't part of Amphi ETL since a few releases. What I suspect is it still exist in your Python environment. 
How to you run Amphi and do you use virtual environment (venv)?
If yes, just flush your virtual environment (remove the folder associated with it) and install again amphi-etl for the latest version :)

**Comment by simonaubertbd** [comment]
Hello @tgourdel I'm a simple man, i use an amphi start on windows cmd ;)
here is the detail : 
`C:\Users\saubert>amphi start
Received command: start
Workspace directory: .
Port: 8888
IP: localhost
Python executable: C:\Users\saubert\AppData\Local\Programs\Python\Python312\python.exe
Environment PATH: C:\Program Files\Eclipse Adoptium\jdk-21.0.1.12-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\saubert\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\saubert\AppData\Local\Programs\Python\Python312\;C:\Users\saubert\AppData\Local\Microsoft\WindowsApps;;C:\Users\saubert\AppData\Local\Programs\Microsoft VS Code\bin
Running JupyterLab command: C:\Users\saubert\AppData\Local\Programs\Python\Python312\python.exe -m jupyter lab --notebook-dir=. --port=8888 --ip=localhost
[I 2024-07-26 07:30:08.428 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-07-26 07:30:08.442 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-07-26 07:30:08.450 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-07-26 07:30:08.459 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-07-26 07:30:08.459 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-07-26 07:30:08.459 ServerApp] nbdime | extension was successfully linked.
[I 2024-07-26 07:30:18.094 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-07-26 07:30:18.655 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-07-26 07:30:18.659 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-07-26 07:30:18.660 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-07-26 07:30:18.660 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-07-26 07:30:18.688 LabApp] JupyterLab extension loaded from C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyterlab
[I 2024-07-26 07:30:18.688 LabApp] JupyterLab application directory is C:\Users\saubert\AppData\Local\Programs\Python\Python312\share\jupyter\lab
[I 2024-07-26 07:30:18.690 LabApp] Extension Manager is 'pypi'.
[I 2024-07-26 07:30:19.092 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-07-26 07:30:19.096 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2024-07-26 07:30:20.839 ServerApp] nbdime | extension was successfully loaded.
[I 2024-07-26 07:30:20.843 ServerApp] Serving notebooks from local directory: C:\Users\saubert
[I 2024-07-26 07:30:20.843 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-07-26 07:30:20.844 ServerApp] http://localhost:8888/lab?token=5d29bc0da6f47ba08be2ffeecdcd16c6500d4b7125b9ba3d
[I 2024-07-26 07:30:20.844 ServerApp]     http://127.0.0.1:8888/lab?token=5d29bc0da6f47ba08be2ffeecdcd16c6500d4b7125b9ba3d
[I 2024-07-26 07:30:20.844 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-07-26 07:30:21.160 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/saubert/AppData/Roaming/jupyter/runtime/jpserver-114328-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=5d29bc0da6f47ba08be2ffeecdcd16c6500d4b7125b9ba3d
        http://127.0.0.1:8888/lab?token=5d29bc0da6f47ba08be2ffeecdcd16c6500d4b7125b9ba3d
[I 2024-07-26 07:30:21.385 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-07-26 07:30:29.925 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-07-26 07:30:30.158 ServerApp.jupyterlab_git] Fail to execute ['git', '--version']
    Traceback (most recent call last):
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyterlab_git\git.py", line 189, in execute
        code, output, error = await current_loop.run_in_executor(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyterlab_git\git.py", line 150, in call_subprocess
        process = subprocess.Popen(
                  ^^^^^^^^^^^^^^^^^
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\saubert\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable`
    
   I have used the jupyter lab at the very beginning

**Comment by tgourdel** [comment]
I see, so if you're not using a Python virtual env, it just means your environment is your laptop. There is nothing wrong really but if for example you want to use Jupyterlab and Amphi at the same time, all the python packages will be installed at the same place which could lead to conflict. To avoid this, we generally use virtual env which isolate each Python environment:)

Anyway, in order to remove this jupyterlab-git extension issue, you can run:
` pip uninstall jupytertlab-git`
Logically, that should remove the issue. Thanks for letting me know

**Comment by simonaubertbd** [comment]
Hello @tgourdel 

I guess something is illogical then ;)
![image](https://github.com/user-attachments/assets/936782b6-1843-4bcc-9c16-05b21452916a)

**Comment by tgourdel** [comment]
Oh sorry my fault, I gave you a command with a typo :s 
` pip uninstall jupyterlab-git
`
There was a 't' that should not have been there

**Comment by simonaubertbd** [comment]
@tgourdel ooopsie I didn't even check myself.

Yep, it worked, thanks !

**Comment by tgourdel** [comment]
Great, was doubting for a moment :p 
I removed the jupyterlab-git extension from the amphi-etl package as I think it's best to let users decide if they want to install it or not. Thanks for reporting.
