### ISSUE TITLE
Slow database extraction

### ISSUE THREAD

**Issue by tgourdel** [amphi-ai/amphi-etl#70]
Extraction is relatively slow compared to other means.
https://amphi-ai.slack.com/archives/C0780QJ8Q9G/p1722587785613949

**Comment by tgourdel** [comment]
@simonaubertbd
I was wondering, do you experience still long waiting times with Postgres or other database systems for reading data? I know you had an issue that we resolved so wondering if that was the same here :)

**Comment by simonaubertbd** [comment]
Hello @tgourdel  Let's say it's way better than before but still slower than Alteryx (4.2 versus 2.4 seconds). I think you can close the ticket for now.

Best regards,

Simon
