### ISSUE TITLE
CSV File Input: Selecting header from configuration does not generate valid pandas code

### ISSUE THREAD

**Issue by vanandjiwala** [amphi-ai/amphi-etl#71]
### Version
amphi-etl==0.5.5
jupyterlab-amphi==0.5.5

### File for testing
[NVDA.csv](https://github.com/user-attachments/files/16477921/NVDA.csv)

### OS
Mac Os

### Browser
Brave. Chromium based

### Steps to reproduce:
1. Create a CSV File Input
2. Upload the file attached with this ticket (Any valid csv file with header should be fine)
3. Click on configure button (Gear Icon)
4. Under header, Select **First Line**.
5. Click "OK" button and run (Play button icon)
6. Here is the error message received:
```
invalid syntax (279378395.py, line 10)
[Show Traceback](http://localhost:8888/lab/workspaces/auto-z/tree/nvda-2020.ampln#)
Cell In[8], line 10
csvFileInput1 = pd.read_csv("NVDA.csv", sep=",", header="0", names=).convert_dtypes()
```

Since names are not passed, i believe the error must have appeared. 
7. click on configuration and write column names as below:
Date,Open,High,Low,Close,Adj Close,Volume
8. 5. Click "OK" button and run (Play button icon)
9. Here is the error I received:
```
invalid syntax. Perhaps you forgot a comma? (2623250734.py, line 10)
[Show Traceback](http://localhost:8888/lab/workspaces/auto-z#)
Cell In[10], line 10
csvFileInput1 = pd.read_csv("NVDA.csv", sep=",", header="0", names=Date,Open,High,Low,Close,Adj Close,Volume, on_bad_lines="skip").convert_dtypes()
^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

### Possible solution
Documentation reference - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

- When 'first row' option is selected in that case header is set to **0** which is expected but based on the documentation, it overrides `names` param. So no input is required in that field and if given it will be ignored. 
- names accepts `Sequence of Hashable` -> a list or a tuple. Based on the error, string is getting passed which is causing the component to fail.

**Comment by tgourdel** [comment]
I believe it's fixed, please update Amphi :)
