### ISSUE TITLE
Join dataset tools : ability to choose several columns

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#72]
Hello,

As of today, the Join Dataset tools only allows to have one single column for key. It's more than common to have a "composite" multi-column key for join.

![image](https://github.com/user-attachments/assets/24dc1cae-24b7-4bec-829e-e23ac4484f13)

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks Simon, that's definitely something I missed when I developped the Join component, should not be too complicated to add multi column support. Thanks for pointing it out

**Comment by tgourdel** [comment]
Added in last release :) (0.5.62)
The experience is slightly less friendly than the screenshot probably, maybe it will be an improvement for the future. For now you have to select the left columns in the order you want them to be match with the right columns.

![image](https://github.com/user-attachments/assets/88799839-533c-447b-9880-8dc3a8141313)

Thank you for reporting this missing feature!
