### ISSUE TITLE
when displaying "small icon", the "configuration" and "run" button should stay visible

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#78]
Hello,

Here a worfklow
![image](https://github.com/user-attachments/assets/07cefb78-9ea2-495b-b2a1-075e6ffb49dc)

When I zoom out, it becomes that, with "small icons" mode (don't know the exact name)
![image](https://github.com/user-attachments/assets/cdf4344d-fee5-4082-b5ce-fe8665cf8558)

Pretty nice, I like it... but the configuration and run buttons are not displayed, and I have to zoom in again.
![image](https://github.com/user-attachments/assets/05469841-b845-42a7-918b-a4b16ca36164)

Best regards,

Simon

PS : there is, I think, too much of "grey space" on the small icon mode.

**Comment by tgourdel** [comment]
Hi Simon,
Yeah the config and run buttons are not shown when dezooming, it was actually like that before introducing the buttons outside of the components and I developed it that way. Now, I haven't put too much thought on it, it looks like you'd expect to access them even when the flow is zoomed out, that make sense. Suggestion duely noted :)
Thanks a lot again!

**Comment by tgourdel** [comment]
So, in case we have many components on the canvas, the buttons appear when you select the component. I think that's a good solution, let me know :) Avail in v0.8.4

**Comment by tgourdel** [comment]
Oh great catch, an oversight :o

**Comment by tgourdel** [comment]
Fixed in 0.8.5, thanks :) Might happen with others, be on the look out
