### ISSUE TITLE
Amphi launched on windows : not working with computer name

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#8]
Hello,

I have installed and launched amphi
![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/f16d62da-b1c9-4a68-ae3d-81a5fdaaf692)

amphi open a tab on my default browser (still ok)
however the adress doesn't work
![image](https://github.com/amphi-ai/amphi-etl/assets/46959192/ee6f7abf-6436-4cc0-88d2-92ff29a7fbbb)

I had to use localhost instead. 

I think :
-let localhost be the adress
-in the meantime, a tip in the documentation

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks a lot @simonaubertbd 🙏 I had not encountered this issue in my tests, I'll investigate!

**Comment by tgourdel** [comment]
This should use localhost by default, and avoid this issue on Windows. To be confirmed by tests.

**Comment by tgourdel** [comment]
Fix verified by tests on Windows. For information, the IP used by Amphi ETL can be modified using the parameter -i:
`amphi start -i localhost` or if using on a server: to expose the service `amphi start -i 0.0.0.0`
