### ISSUE TITLE
Aggregate tool : new operations needed

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#82]
Hello,

As of today, the aggregate tool proposes : Sum, Min, Min, Mean and Count.

I often use:
-avg (I guess it's mean but I think the good term is Avg)
-concat (like transformating toto and titi in toto/titi) with a distinct option and the choice of separator
-count distinct
-first
-longest/shortest (for string)

Best regards,

Simon

**Comment by tgourdel** [comment]
Interesting, great suggestions.
Average and Mean are mathematically the same term if I'm not wrong. Average being more commonly used in British English while mean is more used in American English ;)
Thanks Simon!

**Comment by tgourdel** [comment]
Hi Simon, I've added multiple new functions, thanks for the suggestions.
For any other options, I'll introduce the ability to use custom functions soon based on the work done for the formula component (#27).
![image](https://github.com/user-attachments/assets/7d96b291-6302-4187-96dc-8726110df346)

I'm closing this one and will open a specific issue for the custom functions (#104).
Thanks!!
