### ISSUE TITLE
Sort rows tool : order (ASC/DESC) by field 

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#84]
Hello,

As of today, you can choose several fields for sorting on the sort row tool but only sort order (that applies for each field I guess)

![image](https://github.com/user-attachments/assets/feca32a8-dd66-457d-b3b9-47c8101e5e5e)

I would like to have a separate, distinct order by field, like class asc, colour desc, etc..

Best regards,

Simon

**Comment by tgourdel** [comment]
That's a good point!
Thanks Simon :)

**Comment by tgourdel** [comment]
Hi @simonaubertbd, I've updated the sort component based on your feedback. Now you select a column and its associated sorting order. Hope that's more useful now :)

**Comment by simonaubertbd** [comment]
@tgourdel Thanks, it's way better like that (maybe there is still an improvement : right now, you can choose several times the same field... but that's a detail)

Best regards,

Simon

**Comment by tgourdel** [comment]
Thanks, good catch, forgot to implement this detail ;)
