### ISSUE TITLE
A tool to browse dataframe

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#85]
Hello,

As ot today, you can have a look at your datafram with the console (with a sample of data but you don't know how)

![image](https://github.com/user-attachments/assets/7bd66695-6196-4775-b04a-ea57e217edb9)

or the console tool (note that it's not in "table" formatted)

![image](https://github.com/user-attachments/assets/07b745bf-f458-452a-b280-060b52e26981)

We could imagine something very used on Alteryx : the "browse tool" that allow you to set the sample size (just like the console too) but when clicking on it after execution, it displays the dataframe (at the same place than the console). you can even imagine an option of the pipeline to not display dataframe on the console,which save space.

Example : execution console
![image](https://github.com/user-attachments/assets/35a7dfc4-3350-45cb-9fa8-8a1bfdfe0da0)

Result of the browse tool. Note it's interactive
![image](https://github.com/user-attachments/assets/084e8d51-7bf2-4f71-9f1d-85f539ec43a9)

Best regards,

Simon

**Comment by tgourdel** [comment]
Hi Simon, thanks, had in mind something around what you suggest. Wondering, does the transformation available on columns (Data Cleanse, Filter, Sort) are actually modifying the data down the pipeline or is this just to browse the data?

**Comment by simonaubertbd** [comment]
@tgourdel No, it's just to browse the data. Like if you have a mini-excel on the ui. Also, there's nothing after that tool, it's a dead end. We usually put it every time we have to check (so several tools).

![image](https://github.com/user-attachments/assets/0fa1699c-da4b-46e7-bacc-7bc49f6e455a)

**Comment by tgourdel** [comment]
Released in 0.8.0 as an option when right-clicking "Browse Data". Closing since improvements have been suggested in different issues #170 #171 #172 #173
