### ISSUE TITLE
A simple embedded input tool

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#90]
Hello,

Sometimes, you don't have a file but you need some data in a table. A common solution is to allow the user to create an "embedded" table in the pipeline, when the user specify the columns, the type and the value.

![image](https://github.com/user-attachments/assets/c1696cc5-8d06-40d7-948e-320b703dd72e)

it's also done on qlik sense with the famous "load inline" command

`Table:

LOAD * Inline [

ID  , brand , criteria        ,    assesement

123 , abc ,   Q9,                   Y

145 , abc ,   Q9,                   Y

123 , abc ,   P11,                  Y

145 , abc ,   P11,                  N

];`
Best regards,

Simon

**Comment by tgourdel** [comment]
Added an Inline Input component (in 0.5.72) which is more like "load inline' you mentioned. It was the easy way for now. Graphical table is definitely possible but I need some other development I'm planning first.
Thanks for the suggestion!

**Comment by simonaubertbd** [comment]
Hello @tgourdel Thanks, that's cool :)
