### ISSUE TITLE
Variable/constant /parameter management

### ISSUE THREAD

**Issue by simonaubertbd** [amphi-ai/amphi-etl#96]
Hello,

In most deployment in-real life, we use variables/constant/parameter (whatever is the wording), in order to change things like the database, the date, the table.. etc. This constant can be updated manually or coming from a calculation.

I didn't see something like that during my exploration and that would be amazing.

some examples :
![userconst](https://github.com/user-attachments/assets/08dbe062-449a-425b-98d6-8912caf3887d)
![variables-found](https://github.com/user-attachments/assets/a008347b-32ae-41cf-823b-64d5db65e55a)
![Using-a-Parameter-in-a-Calculation-Parameters-in-Tableau-Edureka](https://github.com/user-attachments/assets/a78c90c9-d56d-4155-a6bd-9c4127b44525)
![156959_variable](https://github.com/user-attachments/assets/f1b171cc-8c09-4a94-a1be-05088bba7908)

Best regards,

Simon

**Comment by tgourdel** [comment]
The Env. Variables components are supposed to address this. It can probably be better but I'd be curious to have your feedback on those.
Once defined in a Env. Variable component:
![image](https://github.com/user-attachments/assets/16b544ba-99d3-4b48-bccf-acc89fc340e4)
Then in all input fields you can click on the brackets on the right of the input and select the Environment Variable:
![image](https://github.com/user-attachments/assets/fe5ec75b-0691-4faa-9dfd-92d76a750940)

**Comment by simonaubertbd** [comment]
@tgourdel  Oooopsie, seems I didn't do my homeworks correctly. I will have a try !

**Comment by tgourdel** [comment]
To be fair, there is no documentation :s 
I was hoping you had caught the little parenthesis/brackets :D 
If you have any feedback on the usability let me know

**Comment by simonaubertbd** [comment]
@tgourdel  My pipeline
![image](https://github.com/user-attachments/assets/d4f9a807-4a60-466d-8791-944b2d1ab65b)


env configuration

![image](https://github.com/user-attachments/assets/59a95218-9eff-4e68-bda4-01ffc0b10301)


CSV input configuration
![image](https://github.com/user-attachments/assets/116040ea-17f7-4d46-8bb8-4c98a0e1a132)

Error message in console

> Error

'function' object is not subscriptable
[Show Traceback](http://localhost:8888/lab/tree/untitled11.ampln#)

---------------------------------------------------------------------------
TypeError Traceback (most recent call last)
Cell In[4], line 15
9 os.environ["v_var_path"] = "simon"
14 # Reading data from tests_amphi/aaaaaaa_{os.getenv['v_var_path']}_aaaa.csv
---> 15 csvFileInput1 = pd.read_csv(f"tests_amphi/aaaaaaa_{os.getenv['v_var_path']}_aaaa.csv", sep=",").convert_dtypes()
17 csvFileInput1

TypeError: 'function' object is not subscriptable

So it doesn't work as I would like to :(

Best regards,

Simon

**Comment by tgourdel** [comment]
Oops, yeah, that's a bug, the correct way to call an env variable is `{os.getenv('v_var_path')}`, it's fixed and will publish a new release later today.
Thanks for testing and letting me know

**Comment by tgourdel** [comment]
Should be fixed with latest version! Thanks Simon
